pipeline {
  agent any

  stages{
      stage('check') {
        sh 'ls ~/.ssh/'
    }
    stage('API') {
      steps {
        dir("mainInstance/ansible/") {
            sh 'ansible-playbook -i inventory provision_api.yml'
        }
      }
    }
    stage('WORKER') {
      steps {
        dir("mainInstance/ansible/") {
            sh 'ansible-playbook -i inventory provision_worker.yml'
        }
      }
    }
  }
}