pipeline {
  agent any

  stages{
    stage('DB') {
      steps {
        dir("mainInstance/ansible/") {
            sh 'ansible-playbook -i inventory provision_db.yml'
        }
      }
    }
    stage('WORKER') {
      steps {
        dir("mainInstance/ansible/") {
            sh 'ansible-playbook -i inventory provision_worker.yml'
        }
      }
    }
    stage('API') {
      steps {
        dir("mainInstance/ansible/") {
            sh 'ansible-playbook -i inventory provision_api.yml'
        }
      }
    }
  }
}