- name: Provision API Servers
  hosts: APIServers
  tasks:

    - name: Install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes

    - name: Install python docker sdk
      shell: |
        pip3 install docker
      become: yes

    - name: Install docker
      apt:
        name: docker.io
      become: yes
    
    - name: Install docker-compose
      apt:
        name: docker-compose
      become: yes

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
      become: yes

    - name: Clone github repository
      git:
       repo: https://github.com/BaptisteBergmann/qmk_web_stack.git
       dest: /home/ubuntu/qmk_web_stack
       clone: yes
       update: yes
       recursive: yes

    - name: build docker
      command: chdir=/home/ubuntu/qmk_web_stack/API sudo docker-compose build

    - name: run docker
      command: chdir=/home/ubuntu/qmk_web_stack/API sudo docker-compose up -d