pipeline {
  agent any

  stages{
    
    stage('terraform init') {
      steps {
        dir("mainInstance/terraform/") {
            sh 'terraform init'
        }
      }
    }
    stage('terraform apply') {
      steps {
        dir("mainInstance/terraform/") {
            sh 'terraform apply -auto-approve -no-color'
        }
      }
    }
  }
}